CREATE TABLE Locations
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Name      VARCHAR(255),
    UserId    INTEGER                                  NOT NULL,
    Latitude  DECIMAL,
    Longitude DECIMAL,
    CONSTRAINT pk_locations PRIMARY KEY (id)
);

CREATE TABLE Sessions
(
    id        UUID    NOT NULL,
    UserId    INTEGER NOT NULL,
    ExpiresAt TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_sessions PRIMARY KEY (id)
);

CREATE TABLE Users
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Login        VARCHAR(255),
    Password VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);